services:
  app:
    build: .
  #  descomenta esto para conectarte desde el host directamente a flask sin pasar por nginx
  #  ports:
  #    - "5000:5000"
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=myflaskapp
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
    # creación de volumen para persistencia
    # - mysql-data:/var/lib/mysql  
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  
      - ./nginx/ssl:/etc/nginx/ssl 
    ports:
      - "443:443" 
      - "80:80"   
    depends_on:
      - app 

      # Para crear un nuevo certificado y clave: $ openssl req -x509 -newkey rsa:4096 -keyout ./nginx/ssl/nginx.key -out ./nginx/ssl/nginx.crt -days 365 -nodes -subj "/CN=localhost"